### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by jade243** [unige-pinfo-2019/slides#1]
Hi, is it possible to upload the installation instructions we've seen on last Friday to install the development
environment. Thanks in advance.

**Comment by stklik** [comment]
Hi, the project repository is https://github.com/hostettler/microservices

Please create an issue directly there, so @hostettler sees it directly.

**Comment by stklik** [comment]
Steve provided a link to http://www.hostettler.net/2019/02/17/microservice-architecture-part-1.html
